### ISSUE TITLE
使用イメージ、および設計思想に関して

### ISSUE THREAD

**Issue by D4prog** [support-project/docker-knowledge#7]
docker公式の `tomcat:jre8` イメージを使用せず、素のOSから環境を構築しているのが気になりましたため、質問させていただきます。
(`tomcat:jre8` は、現行のdocker-knowledgeと同じく、tomcat8, openjdk-8-jre-headless を使用しています)

Dockerfileの方向性として、イメージサイズの削減や表現(と意図)の簡潔さなどが考えられますが、どのような意図のもとで現在の状態にありますでしょうか。

**Comment by koda-masaru** [comment]
D4progさん

今までのDockerfileですが、特に思想などはありませんでした（期待に沿う答えでは無くてすみません）
というのも、Knowledgeのデモサイトに「このDockerfileで動くよ！」という投稿があったので、それをそのまま使わせてもらっている状況です。（いったんは、簡単に導入できればOKかなと思ってました）

しかしながら、多くの利用者もいることですし、Dockerfileの方向性をも検討した方が良いですね。
そうすると、重視しなければいけない事は以下になるのかなと思います。（優先度順）
1. セキュアであること
2. イメージサイズが小さいこと
3. 表現が簡潔であること

利用者によっては、Dockerfileの中まで見ないという人もいるかと思います。
また、DockerHubに登録して、直接イメージを取得という使い方もアリかと思います。
そう考えると、「記述の簡潔さ」より、「セキュアでかつ軽い」という方が喜ばれるかと思いました。

このような答えでいかがでしょうか？
